import { boldMinValue, addRank, sortByAll } from "./utils";

let frontalViewData: Data[] = [
  {
    nose_avg: { val: "1.719", bold: false },
    nose_med: { val: "1.683", bold: false },
    nose_std: { val: "0.354", bold: false },
    mouth_avg: { val: "1.368", bold: false },
    mouth_med: { val: "1.301", bold: false },
    mouth_std: { val: "0.439", bold: false },
    forehead_avg: { val: "2.015", bold: false },
    forehead_med: { val: "2.007", bold: false },
    forehead_std: { val: "0.449", bold: false },
    cheek_avg: { val: "1.528", bold: false },
    cheek_med: { val: "1.442", bold: false },
    cheek_std: { val: "0.501", bold: false },
    all_avg: { val: "1.657", bold: false },
    method: "Deep3D",
    link: "https://arxiv.org/pdf/1903.08527.pdf",
  },
  {
    nose_avg: { val: "1.771", bold: false },
    nose_med: { val: "1.741", bold: false },
    nose_std: { val: "0.380", bold: false },
    mouth_avg: { val: "1.417", bold: false },
    mouth_med: { val: "1.355", bold: false },
    mouth_std: { val: "0.409", bold: false },
    forehead_avg: { val: "2.268", bold: false },
    forehead_med: { val: "2.215", bold: false },
    forehead_std: { val: "0.503", bold: false },
    cheek_avg: { val: "1.639", bold: false },
    cheek_med: { val: "1.494", bold: false },
    cheek_std: { val: "0.650", bold: false },
    all_avg: { val: "1.774", bold: false },
    method: "MGCNet",
    link: "https://arxiv.org/pdf/2007.12494.pdf",
  },
  {
    nose_avg: { val: "1.928", bold: false },
    nose_med: { val: "1.881", bold: false },
    nose_std: { val: "0.490", bold: false },
    mouth_avg: { val: "1.812", bold: false },
    mouth_med: { val: "1.769", bold: false },
    mouth_std: { val: "0.544", bold: false },
    forehead_avg: { val: "2.402", bold: false },
    forehead_med: { val: "3.339", bold: false },
    forehead_std: { val: "0.545", bold: false },
    cheek_avg: { val: "1.329", bold: false },
    cheek_med: { val: "1.234", bold: false },
    cheek_std: { val: "0.504", bold: false },
    all_avg: { val: "1.868", bold: false },
    method: "GANFit",
    link: "https://arxiv.org/pdf/1902.05978.pdf",
  },
  {
    nose_avg: { val: "1.791", bold: false },
    nose_med: { val: "1.724", bold: false },
    nose_std: { val: "0.542", bold: false },
    mouth_avg: { val: "1.591", bold: false },
    mouth_med: { val: "1.551", bold: false },
    mouth_std: { val: "0.488", bold: false },
    forehead_avg: { val: "2.413", bold: false },
    forehead_med: { val: "2.351", bold: false },
    forehead_std: { val: "0.537", bold: false },
    cheek_avg: { val: "1.856", bold: false },
    cheek_med: { val: "1.737", bold: false },
    cheek_std: { val: "0.701", bold: false },
    all_avg: { val: "1.913", bold: false },
    method: "SADRNet",
    link: "https://arxiv.org/pdf/2106.03021.pdf",
  },
  {
    nose_avg: { val: "1.903", bold: false },
    nose_med: { val: "1.857", bold: false },
    nose_std: { val: "0.517", bold: false },
    mouth_avg: { val: "1.597", bold: false },
    mouth_med: { val: "1.529", bold: false },
    mouth_std: { val: "0.478", bold: false },
    forehead_avg: { val: "2.447", bold: false },
    forehead_med: { val: "3.356", bold: false },
    forehead_std: { val: "0.647", bold: false },
    cheek_avg: { val: "1.757", bold: false },
    cheek_med: { val: "1.683", bold: false },
    cheek_std: { val: "0.642", bold: false },
    all_avg: { val: "1.926", bold: false },
    method: "3DDFA-v2",
    link: "https://arxiv.org/pdf/2009.09960.pdf",
  },
  {
    nose_avg: { val: "1.697", bold: false },
    nose_med: { val: "1.654", bold: false },
    nose_std: { val: "0.355", bold: false },
    mouth_avg: { val: "2.516", bold: false },
    mouth_med: { val: "2.465", bold: false },
    mouth_std: { val: "0.839", bold: false },
    forehead_avg: { val: "2.394", bold: false },
    forehead_med: { val: "2.256", bold: false },
    forehead_std: { val: "0.576", bold: false },
    cheek_avg: { val: "1.479", bold: false },
    cheek_med: { val: "1.400", bold: false },
    cheek_std: { val: "0.535", bold: false },
    all_avg: { val: "2.010", bold: false },
    method: "DECA-c",
    link: "https://arxiv.org/pdf/2012.04012.pdf",
  },
  {
    nose_avg: { val: "1.923", bold: false },
    nose_med: { val: "1.811", bold: false },
    nose_std: { val: "0.518", bold: false },
    mouth_avg: { val: "1.838", bold: false },
    mouth_med: { val: "1.699", bold: false },
    mouth_std: { val: "0.637", bold: false },
    forehead_avg: { val: "2.429", bold: false },
    forehead_med: { val: "2.329", bold: false },
    forehead_std: { val: "0.588", bold: false },
    cheek_avg: { val: "1.863", bold: false },
    cheek_med: { val: "1.715", bold: false },
    cheek_std: { val: "0.698", bold: false },
    all_avg: { val: "2.013", bold: false },
    method: "PRNet",
    link: "https://arxiv.org/pdf/1803.07835.pdf",
  },
  {
    nose_avg: { val: "2.779", bold: false },
    nose_med: { val: "2.717", bold: false },
    nose_std: { val: "0.835", bold: false },
    mouth_avg: { val: "1.448", bold: false },
    mouth_med: { val: "1.438", bold: false },
    mouth_std: { val: "0.406", bold: false },
    forehead_avg: { val: "2.384", bold: false },
    forehead_med: { val: "2.302", bold: false },
    forehead_std: { val: "0.578", bold: false },
    cheek_avg: { val: "1.456", bold: false },
    cheek_med: { val: "1.321", bold: false },
    cheek_std: { val: "0.485", bold: false },
    all_avg: { val: "2.017", bold: false },
    method: "CEST",
    link: "https://arxiv.org/pdf/2110.04800.pdf",
  },
  {
    nose_avg: { val: "2.026", bold: false },
    nose_med: { val: "2.014", bold: false },
    nose_std: { val: "0.532", bold: false },
    mouth_avg: { val: "1.731", bold: false },
    mouth_med: { val: "1.724", bold: false },
    mouth_std: { val: "0.502", bold: false },
    forehead_avg: { val: "2.679", bold: false },
    forehead_med: { val: "2.615", bold: false },
    forehead_std: { val: "0.741", bold: false },
    cheek_avg: { val: "1.647", bold: false },
    cheek_med: { val: "1.550", bold: false },
    cheek_std: { val: "0.622", bold: false },
    all_avg: { val: "2.021", bold: false },
    method: "SynergyNet",
    link: "https://arxiv.org/pdf/2110.09772.pdf",
  },
  {
    nose_avg: { val: "2.138", bold: false },
    nose_med: { val: "2.137", bold: false },
    nose_std: { val: "0.461", bold: false },
    mouth_avg: { val: "2.802", bold: false },
    mouth_med: { val: "2.699", bold: false },
    mouth_std: { val: "0.868", bold: false },
    forehead_avg: { val: "2.457", bold: false },
    forehead_med: { val: "2.341", bold: false },
    forehead_std: { val: "0.559", bold: false },
    cheek_avg: { val: "1.443", bold: false },
    cheek_med: { val: "1.353", bold: false },
    cheek_std: { val: "0.498", bold: false },
    all_avg: { val: "2.210", bold: false },
    method: "DECA-f",
    link: "https://arxiv.org/pdf/2012.04012.pdf",
  },
  {
    nose_avg: { val: "1.934", bold: false },
    nose_med: { val: "1.907", bold: false },
    nose_std: { val: "0.458", bold: false },
    mouth_avg: { val: "2.074", bold: false },
    mouth_med: { val: "1.991", bold: false },
    mouth_std: { val: "0.616", bold: false },
    forehead_avg: { val: "2.995", bold: false },
    forehead_med: { val: "2.852", bold: false },
    forehead_std: { val: "0.908", bold: false },
    cheek_avg: { val: "2.028", bold: false },
    cheek_med: { val: "1.937", bold: false },
    cheek_std: { val: "0.720", bold: false },
    all_avg: { val: "2.258", bold: false },
    method: "RingNet",
    link: "https://arxiv.org/pdf/1905.06817.pdf",
  },
  {
    nose_avg: { val: "2.509", bold: false },
    nose_med: { val: "2.463", bold: false },
    nose_std: { val: "0.486", bold: false },
    mouth_avg: { val: "1.912", bold: false },
    mouth_med: { val: "1.850", bold: false },
    mouth_std: { val: "0.450", bold: false },
    forehead_avg: { val: "3.084", bold: false },
    forehead_med: { val: "2.879", bold: false },
    forehead_std: { val: "1.005", bold: false },
    cheek_avg: { val: "1.717", bold: false },
    cheek_med: { val: "1.642", bold: false },
    cheek_std: { val: "0.590", bold: false },
    all_avg: { val: "2.306", bold: false },
    method: "ExpNet",
    link: "https://arxiv.org/pdf/1802.00542.pdf",
  },
  {
    nose_avg: { val: "2.936", bold: false },
    nose_med: { val: "2.857", bold: false },
    nose_std: { val: "0.810", bold: false },
    mouth_avg: { val: "2.375", bold: false },
    mouth_med: { val: "2.390", bold: false },
    mouth_std: { val: "0.599", bold: false },
    forehead_avg: { val: "4.582", bold: false },
    forehead_med: { val: "4.452", bold: false },
    forehead_std: { val: "1.488", bold: false },
    cheek_avg: { val: "1.918", bold: false },
    cheek_med: { val: "1.717", bold: false },
    cheek_std: { val: "0.801", bold: false },
    all_avg: { val: "2.953", bold: false },
    method: "N-3DMM",
    link: "https://arxiv.org/pdf/1804.03786.pdf",
  },
  {
    nose_avg: { val: "1.585", bold: false },
    nose_med: { val: "1.542", bold: false },
    nose_std: { val: "0.325", bold: false },
    mouth_avg: { val: "3.478", bold: false },
    mouth_med: { val: "3.439", bold: false },
    mouth_std: { val: "1.204", bold: false },
    forehead_avg: { val: "2.374", bold: false },
    forehead_med: { val: "2.251", bold: false },
    forehead_std: { val: "0.683", bold: false },
    cheek_avg: { val: "1.099", bold: false },
    cheek_med: { val: "1.003", bold: false },
    cheek_std: { val: "0.324", bold: false },
    all_avg: { val: "2.134", bold: false },
    method: "MICA",
    link: "https://arxiv.org/pdf/2204.06607.pdf",
  },
  {
    nose_avg: { val: "1.868", bold: false },
    nose_med: { val: "1.821", bold: false },
    nose_std: { val: "0.387", bold: false },
    mouth_avg: { val: "2.679", bold: false },
    mouth_med: { val: "2.419", bold: false },
    mouth_std: { val: "1.112", bold: false },
    forehead_avg: { val: "2.426", bold: false },
    forehead_med: { val: "2.383", bold: false },
    forehead_std: { val: "0.641", bold: false },
    cheek_avg: { val: "1.438", bold: false },
    cheek_med: { val: "1.294", bold: false },
    cheek_std: { val: "0.501", bold: false },
    all_avg: { val: "2.103", bold: false },
    method: "EMOCA-c",
    link: "https://arxiv.org/pdf/2204.11312.pdf",
  },
  {
    nose_avg: { val: "2.532", bold: false },
    nose_med: { val: "2.563", bold: false },
    nose_std: { val: "0.539", bold: false },
    mouth_avg: { val: "2.929", bold: false },
    mouth_med: { val: "2.676", bold: false },
    mouth_std: { val: "1.106", bold: false },
    forehead_avg: { val: "2.595", bold: false },
    forehead_med: { val: "2.505", bold: false },
    forehead_std: { val: "0.631", bold: false },
    cheek_avg: { val: "1.495", bold: false },
    cheek_med: { val: "1.360", bold: false },
    cheek_std: { val: "0.469", bold: false },
    all_avg: { val: "2.388", bold: false },
    method: "EMOCA-f",
    link: "https://arxiv.org/pdf/2204.11312.pdf",
  },
  {
    nose_avg: { val: "1.722", bold: false },
    nose_med: { val: "1.685", bold: false },
    nose_std: { val: "0.330", bold: false },
    mouth_avg: { val: "1.357", bold: false },
    mouth_med: { val: "1.226", bold: false },
    mouth_std: { val: "0.523", bold: false },
    forehead_avg: { val: "1.995", bold: false },
    forehead_med: { val: "1.990", bold: false },
    forehead_std: { val: "0.476", bold: false },
    cheek_avg: { val: "1.072", bold: false },
    cheek_med: { val: "1.063", bold: false },
    cheek_std: { val: "0.333", bold: false },
    all_avg: { val: "1.537", bold: false },
    method: "HRN",
    link: "https://arxiv.org/pdf/2302.14434.pdf",
  },
  {
    nose_avg: { val: "1.656", bold: false },
    nose_med: { val: "1.636", bold: false },
    nose_std: { val: "0.374", bold: false },
    mouth_avg: { val: "2.087", bold: false },
    mouth_med: { val: "1.927", bold: false },
    mouth_std: { val: "0.839", bold: false },
    forehead_avg: { val: "2.102", bold: false },
    forehead_med: { val: "2.035", bold: false },
    forehead_std: { val: "0.512", bold: false },
    cheek_avg: { val: "1.141", bold: false },
    cheek_med: { val: "1.103", bold: false },
    cheek_std: { val: "0.303", bold: false },
    all_avg: { val: "1.746", bold: false },
    method: "AlbedoGAN",
    link: "https://arxiv.org/pdf/2304.12483.pdf",
  },
  {
    nose_avg: { val: "2.516", bold: false },
    nose_med: { val: "2.382", bold: false },
    nose_std: { val: "0.643", bold: false },
    mouth_avg: { val: "2.569", bold: false },
    mouth_med: { val: "2.540", bold: false },
    mouth_std: { val: "0.597", bold: false },
    forehead_avg: { val: "2.350", bold: false },
    forehead_med: { val: "2.184", bold: false },
    forehead_std: { val: "0.636", bold: false },
    cheek_avg: { val: "2.261", bold: false },
    cheek_med: { val: "2.205", bold: false },
    cheek_std: { val: "0.529", bold: false },
    all_avg: { val: "2.424", bold: false },
    method: "FS-Opt-c",
    link: "https://arxiv.org/pdf/2003.13989.pdf",
  },
  {
    nose_avg: { val: "2.474", bold: false },
    nose_med: { val: "2.352", bold: false },
    nose_std: { val: "0.636", bold: false },
    mouth_avg: { val: "2.539", bold: false },
    mouth_med: { val: "2.495", bold: false },
    mouth_std: { val: "0.600", bold: false },
    forehead_avg: { val: "2.341", bold: false },
    forehead_med: { val: "2.175", bold: false },
    forehead_std: { val: "0.632", bold: false },
    cheek_avg: { val: "2.259", bold: false },
    cheek_med: { val: "2.205", bold: false },
    cheek_std: { val: "0.526", bold: false },
    all_avg: { val: "2.403", bold: false },
    method: "FS-Opt-f",
    link: "https://arxiv.org/pdf/2003.13989.pdf",
  },
  {
    nose_avg: { val: "2.837", bold: false },
    nose_med: { val: "2.877", bold: false },
    nose_std: { val: "0.702", bold: false },
    mouth_avg: { val: "3.312", bold: false },
    mouth_med: { val: "3.327", bold: false },
    mouth_std: { val: "0.712", bold: false },
    forehead_avg: { val: "4.324", bold: false },
    forehead_med: { val: "4.342", bold: false },
    forehead_std: { val: "0.763", bold: false },
    cheek_avg: { val: "2.369", bold: false },
    cheek_med: { val: "2.345", bold: false },
    cheek_std: { val: "0.581", bold: false },
    all_avg: { val: "3.211", bold: false },
    method: "FaceVerse-c",
    link: "https://arxiv.org/pdf/2203.14057.pdf",
  },
  {
    nose_avg: { val: "3.136", bold: false },
    nose_med: { val: "3.132", bold: false },
    nose_std: { val: "0.803", bold: false },
    mouth_avg: { val: "3.532", bold: false },
    mouth_med: { val: "3.364", bold: false },
    mouth_std: { val: "0.683", bold: false },
    forehead_avg: { val: "5.026", bold: false },
    forehead_med: { val: "4.974", bold: false },
    forehead_std: { val: "0.836", bold: false },
    cheek_avg: { val: "2.221", bold: false },
    cheek_med: { val: "2.191", bold: false },
    cheek_std: { val: "0.544", bold: false },
    all_avg: { val: "3.479", bold: false },
    method: "FaceVerse-f",
    link: "https://arxiv.org/pdf/2203.14057.pdf",
  },
  {
    nose_avg: { val: "1.054", bold: false },
    nose_med: { val: "1.021", bold: false },
    nose_std: { val: "0.317", bold: false },
    mouth_avg: { val: "1.461", bold: false },
    mouth_med: { val: "1.381", bold: false },
    mouth_std: { val: "0.430", bold: false },
    forehead_avg: { val: "1.331", bold: false },
    forehead_med: { val: "1.307", bold: false },
    forehead_std: { val: "0.347", bold: false },
    cheek_avg: { val: "1.342", bold: false },
    cheek_med: { val: "1.304", bold: false },
    cheek_std: { val: "0.384", bold: false },
    all_avg: { val: "1.297", bold: false },
    method: "HiFace-c",
    link: "https://arxiv.org/pdf/2303.11225.pdf",
  },
  {
    nose_avg: { val: "1.036", bold: false },
    nose_med: { val: "0.992", bold: false },
    nose_std: { val: "0.280", bold: false },
    mouth_avg: { val: "1.450", bold: false },
    mouth_med: { val: "1.388", bold: false },
    mouth_std: { val: "0.413", bold: false },
    forehead_avg: { val: "1.324", bold: false },
    forehead_med: { val: "1.296", bold: false },
    forehead_std: { val: "0.334", bold: false },
    cheek_avg: { val: "1.291", bold: false },
    cheek_med: { val: "1.240", bold: false },
    cheek_std: { val: "0.362", bold: false },
    all_avg: { val: "1.275", bold: false },
    method: "HiFace-f",
    link: "https://arxiv.org/pdf/2303.11225.pdf",
  },
  {
    nose_avg: { val: "1.708", bold: false },
    nose_med: { val: "1.688", bold: false },
    nose_std: { val: "0.349", bold: false },
    mouth_avg: { val: "1.876", bold: false },
    mouth_med: { val: "1.777", bold: false },
    mouth_std: { val: "0.563", bold: false },
    forehead_avg: { val: "2.350", bold: false },
    forehead_med: { val: "2.343", bold: false },
    forehead_std: { val: "0.551", bold: false },
    cheek_avg: { val: "1.593", bold: false },
    cheek_med: { val: "1.482", bold: false },
    cheek_std: { val: "0.540", bold: false },
    all_avg: { val: "1.882", bold: false },
    method: "PSL",
    link: "https://arxiv.org/pdf/2310.19580",
  },
  {
    nose_avg: { val: "1.499", bold: false },
    nose_med: { val: "1.423", bold: false },
    nose_std: { val: "0.366", bold: false },
    mouth_avg: { val: "1.424", bold: false },
    mouth_med: { val: "1.340", bold: false },
    mouth_std: { val: "0.462", bold: false },
    forehead_avg: { val: "1.950", bold: false },
    forehead_med: { val: "1.867", bold: false },
    forehead_std: { val: "0.559", bold: false },
    cheek_avg: { val: "1.128", bold: false },
    cheek_med: { val: "1.057", bold: false },
    cheek_std: { val: "0.303", bold: false },
    all_avg: { val: "1.500", bold: false },
    method: "MoSAR",
    link: "https://arxiv.org/pdf/2312.13091",
  },
];

frontalViewData = sortByAll(frontalViewData);
addRank(frontalViewData);
boldMinValue(frontalViewData);

export { frontalViewData };
