#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# smartly lint only the files that you're trying to commit, instead of the whole repo
# runs commands set in the .lintstagedrc.js file, based on file extension
npx lint-staged

# or if you want to lint the whole repo before commit (will become slower as project grows):
# npm run lint
