name: Jekyll site CI

on:
  push:
    branches: [ "vue" ]
  pull_request:
    branches: [ "vue" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
    
    - name: install and build
      run: |
        npm install
        npm run build
        
    - name: deploy
      run: |
        cd dist
        echo > .nojekyll
        
        git init
        git checkout -B main
        git add -A
        git commit -m 'deploy'
        git push -f git@github.com:czh-98/REALY_homepage.git main:gh-pages
